tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "coreutils"
brew "fasd"
brew "git-extras"
brew "gnupg"
brew "mas"
brew "neovim"
brew "reattach-to-user-namespace"
brew "repo"
brew "tig"
brew "tmux"
brew "tree"
brew "unrar"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password6"
cask "alacritty"
cask "appcleaner"
cask "caffeine"
cask "ccmenu"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-drive-file-stream"
cask "joplin"
cask "mattermost"
cask "microsoft-teams"
cask "tomighty"
cask "virtualbox"
cask "visual-studio-code"
cask "zoomus"
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft Excel", id: 462058435
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
