#!/usr/bin/env bash

set -e

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${base_dir}"
echo $base_dir

echo "Update submodules"
git submodule update --init --recursive
git submodule foreach git pull origin master

echo "Ensure symlinks are setup"
dotlinker/link asdf alacritty.yml config gitconfig gitignore_global git-template talisman talisman-precommit-config ideavimrc tmux tmux.conf tool-versions vimrc nvimrc vim

echo "Ensure that homebrew is installed"
hash brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

echo "Ensure brew bundle"
brew bundle

echo "Ensure that ohmyzsh is installed"
sh -c '$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)' || true

echo "Link personal zshrc"
rm -f ~/.zshrc
dotlinker/link zshrc

echo "Ensure that asdf is installed"

install_asdf_plugin() {
  if asdf plugin list | grep $1; then
    echo "$1 already installed"
  else
    asdf plugin add $1;
  fi
}

cd asdf && git checkout "$(git describe --abbrev=0 --tags)" && cd ..
asdf update
install_asdf_plugin "python"
asdf install

echo "Ensure that vim plugins are installed"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
nvim +PlugInstall +PlugUpgrade +PlugUpdate +qall

echo "Ensure that tmux plugins are installed"
~/.tmux/plugins/tpm/bin/install_plugins

echo "Ensure that talisman is installed"
curl --silent https://raw.githubusercontent.com/thoughtworks/talisman/master/global_install_scripts/update_talisman.bash > /tmp/update_talisman.bash && /bin/bash /tmp/update_talisman.bash

echo "Echo what is installed in brew but not in the brewfile"
brew bundle cleanup
